
name: Upload Website 1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIA3QI5SDKN33X6SF4L
          aws-secret-access-key: IAGAhYKOuXdiQZIdpe6haljNw3/o9Zke1ijYe/Jl
          aws-region: us-east-1
      - name: S3 copy
        run: aws s3 sync ./s3_files/.  s3://www.resume.mivancic.com --delete
